In [75]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

In [71]:
df =pd.read_csv("stock.csv")
df

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5    Target
0     1.764052   0.400157   0.978738   2.240893   1.867558 -2.413718
1    -0.977278   0.950088  -0.151357  -0.103219   0.410599 -0.437742
2     0.144044   1.454274   0.761038   0.121675   0.443863 -0.288170
3     0.333674   1.494079  -0.205158   0.313068  -0.854096  0.862693
4    -2.552990   0.653619   0.864436  -0.742165   2.269755 -1.927371
..         ...        ...        ...        ...        ...       ...
295  -0.324730  -0.528870   0.173712   0.566545   0.146304  0.062966
296   0.498727  -0.737932  -1.203735   0.417044   0.687881 -1.313122
297   0.049857   1.348036   0.907699   2.680571  -0.200809 -0.540841
298  -0.998849  -0.740137  -0.565498   0.476031  -2.158069  2.268950
299   1.318551  -0.239297  -0.246794  -1.079343  -0.114226  0.487350

[300 rows x 6 columns]

In [89]:
df.describe().head(2)

Feature_1   Feature_2   Feature_3   Feature_4   Feature_5      Target
count  300.000000  300.000000  300.000000  300.000000  300.000000  300.000000
mean    -0.069664   -0.069389    0.003354    0.000543    0.032962   -0.004584

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Feature_1  300 non-null    float64
 1   Feature_2  300 non-null    float64
 2   Feature_3  300 non-null    float64
 3   Feature_4  300 non-null    float64
 4   Feature_5  300 non-null    float64
 5   Target     300 non-null    float64
dtypes: float64(6)
memory usage: 14.2 KB


In [41]:
x =df.drop(["Target"],axis=1)
y =df["Target"]

In [43]:
x.head(2)

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5
0   1.764052   0.400157   0.978738   2.240893   1.867558
1  -0.977278   0.950088  -0.151357  -0.103219   0.410599

In [45]:
x_train,x_test,y_train,y_test =train_test_split(x,y, test_size=0.2, random_state =42)

In [47]:
model =LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [79]:
y_pred  = model.predict(x_test)

In [81]:
y_pred

array([-0.84281419,  0.67346741, -0.4056025 ,  1.65201863, -0.34449893,
        0.15053871,  0.1622138 , -1.19313457, -2.28728997,  1.36931419,
        0.22102178, -0.95764781, -2.09747996,  0.6699163 ,  2.95669388,
       -1.00453871, -0.65649278,  1.49367515,  1.64921614,  0.49637959,
        1.14859854, -0.27256918,  1.56197889,  0.35661141, -0.16795051,
        1.42846827, -1.08151284, -0.2862791 ,  0.95231221, -1.17550325,
       -0.55024956,  0.67964474, -1.38858101,  0.17257566, -0.24767962,
        0.73087408,  0.8165581 , -0.3810098 ,  0.72742198,  1.11059913,
        0.97937662, -0.30552309,  0.03409462, -0.46233115, -1.48753355,
        0.06941452, -1.10640891, -0.52509407,  1.87479303,  0.60320529,
        0.95014519,  1.88141856,  0.44143562, -1.33951763, -1.19840222,
       -0.40456469, -0.14616384,  0.37104157, -0.01504028,  0.02970644])

In [57]:
model.predict([[1.74052,0.400157,0.978738,2.240893,1.867558]])

/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-2.684553])

In [61]:
model.coef_

array([-0.00159342, -0.14509838,  0.37730107, -0.58456741, -0.92092819])

In [63]:
model.intercept_

0.03684345620943658

In [83]:
mse =mean_squared_error(y_test,y_pred)
mse

0.25624228624908657

In [85]:
r2 = r2_score(y_test,y_pred)
r2

0.8109463739722069